import Head from "next/head";
import React from "react";
import PageLayout from "@/components/PageLayout";
import { FlexColCentered, Form, FormWrapper, H1, SubmitButton } from "@/components/styled-global-components";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { GetServerSideProps } from 'next';
import { Label, Select, TextInput } from "flowbite-react";
import { translateOrDefault } from "@/utils/i18nUtils";

export default function Page() {
  const { t } = useTranslation("common");
  return (
    <>
      <Head>
        <title>Invite User</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <FlexColCentered className="gap-8">
          <H1>{translateOrDefault(t, "pages.inviteUser.heading", "Invite User")}</H1>
          <FormWrapper>
            <Form className="flex flex-col gap-4">
              <div id="select">
                <div className="mb-2 block">
                  <Label
                    htmlFor="company"
                    value={translateOrDefault(t, "pages.inviteUser.form.labels.select-company", "Select Company")}
                  />
                </div>
                <Select id="company" required={true}>
                  <option>Attentus</option>
                  <option>NEM</option>
                </Select>
              </div>
              <div>
                <div className="mb-2 block">
                  <Label
                    htmlFor="full-name"
                    value={translateOrDefault(t, "pages.inviteUser.form.labels.full-name", "Users Full Name")}
                  />
                </div>
                <TextInput
                  id="full-name"
                  type="text"
                  placeholder="Ola Nordmann"
                  required={true}
                />
              </div>
              <div>
                <div className="mb-2 block">
                  <Label
                    htmlFor="email"
                    value={translateOrDefault(t, "pages.inviteUser.form.labels.email", "Email")}
                  />
                </div>
                <TextInput
                  id="email"
                  type="text"
                  placeholder="ola@example.no"
                  required={true}
                />
              </div>
              <SubmitButton
                type="submit"
              >
                {translateOrDefault(t, "pages.inviteUser.form.submit", "Invite")}
              </SubmitButton>
              <Label
                className="text-center"
                value={translateOrDefault(t, "pages.inviteUser.form.labels.submit", "Send invite to new user")}
              />
            </Form>
          </FormWrapper>
        </FlexColCentered>
      </PageLayout>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale as string, ["common"])),
    },
  };
};
