import Head from "next/head";
import React from "react";
import PageLayout from "../components/PageLayout";
import { FlexColContainer, H1 } from "../components/styled-global-components";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { GetServerSideProps } from 'next';
import { translateOrDefault } from "@/utils/i18nUtils";
export default function Home() {
  const { t } = useTranslation("common");
  return (
    <>
      <Head>
        <title>EKKO Media home page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <FlexColContainer className="min-h-full">
          <H1>{translateOrDefault(t, "greeting", "Welcome")}</H1>
        </FlexColContainer>
      </PageLayout>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale as string, ["common"])),
    },
  };
};
