import Head from "next/head";
import { useEffect } from "react"
import React from "react";
import PageLayout from "@/components/landing/PageLayout";
import PageContent from "@/components/landing/";
//import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { GetServerSideProps } from 'next';
//import { translateOrDefault } from "@/utils/i18nUtils";
import { useRouter } from "next/router"

const Page = () => {
  //const { t } = useTranslation("common");

  const router = useRouter();


  useEffect(() => {
    if (typeof window !== 'undefined') {
      const { hash } = window.location;
      const urlParams = new URLSearchParams(window.location.search);
      const code = urlParams.get('code');
      if (hash) {
        const token = hash.split('=')[1];
        console.log(token); // should print your access token
        if (token) {
          router.push("/confirm-email?access_token=" + token);
        }
      }
      if (code) {
        router.push("/confirm-email?access_token=" + code);
      }
    }
  }, [router]);


  return (
    <>
      <Head>
        <title>Templify Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <PageContent />
      </PageLayout>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  return {
    props: {
      ...(await serverSideTranslations(context.locale as string, ["common"]))
    }
  }
}
export default Page;
